name: Build, Release and Firebase Hosting

on:
  # push:
  #   branches: [main]
  release:
    types: [published]

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show hello
        run: echo "Hello wold"

      - name: Create .firebaserc config file
        id: firebaserc
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ".firebaserc"
          encodedString: ${{ secrets.FIREBASERC }}

      - name: Move .firebaserc into project
        run: |
          mv ${{ steps.firebaserc.outputs.filePath }} ./

      - name: Create .env config file
        id: env
        uses: timheuer/base64-to-file@v1
        with:
          fileName: ".env"
          encodedString: ${{ secrets.DOT_ENV }}

      - name: Move .env into project
        run: |
          mv ${{ steps.env.outputs.filePath }} ./

      - name: Import dependencies
        run: npm ci

      - name: Build project
        run: npm run generate

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
